apiVersion: v2
name: visual-regression-tracker
description: Backend and Frontend application for tracking differences via image comparison
home: https://visual-regression-tracker.com
sources:
  - https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker
  - https://github.com/kokuwaio/helm-charts/tree/main/charts/visual-regression-tracker
type: application
version: 0.5.0
appVersion: "4.20.5"
maintainers:
  - name: monotek
    email: monotek23@gmail.com
dependencies:
  - name: postgresql
    version: "11.9.1"
    repository: https://charts.bitnami.com/bitnami
    condition: vrtConfig.postgresql.enabled
