apiVersion: v2
name: nginx-php-fpm
description: A Helm chart for Kubernetes deploying nginx with php fpm
type: application
version: 0.1.3
appVersion: "nginx-1.29.0-alpine3.22-php-8.5.0-fpm-alpine3.22"
maintainers:
  - name: monotek
    email: monotek23@gmail.com
